/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Generations": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GoogleApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InsightSnapshots": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyWeb": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MyWebAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyWebServer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SharedBookmarks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}